/*
 * gpio.h
 *
 *  Created on: 4 feb. 2025
 *      Author: geert
 */

#ifndef REGISTERS_GPIO_H_
#define REGISTERS_GPIO_H_

#include "reg.h"

#define GPIOA_BASE_ADDR (0x48000000)
#define GPIOB_BASE_ADDR (0x48000400)
#define GPIOC_BASE_ADDR (0x48000800)
#define GPIOD_BASE_ADDR (0x48000C00)
#define GPIOE_BASE_ADDR (0x48001000)
#define GPIOF_BASE_ADDR (0x48001400)

/* address offsets for specific gpio registers */
#define GPIOx_MODER 	(0x00) //GPIO port mode register
#define GPIOx_OTYPER 	(0x04) //GPIO port output type register
#define GPIOx_OSPEEDR 	(0x08) //GPIO port output speed register
#define GPIOx_PUPDR 	(0x0c) //GPIO port pull-up/pull-down registe
#define GPIOx_IDR 		(0x10) //GPIO port input data register
#define GPIOx_ODR 		(0x14) //GPIO port output data register
#define GPIOx_BSRR 		(0x18) //GPIO port bit set/reset register
#define GPIOx_LCKR 		(0x1c) //GPIO port configuration lock register
#define GPIOx_AFRL 		(0x20) //GPIO alternate function low register
#define GPIOx_AFRH 		(0x24) //GPIO alternate function high register
#define GPIOx_BRR 		(0x28) //GPIO port bit reset register

#define GPIOA_MODER     REG(GPIOA_BASE_ADDR + GPIOx_MODER)
#define GPIOA_OTYPER    REG(GPIOA_BASE_ADDR + GPIOx_OTYPER)
#define GPIOA_OSPEEDR   REG(GPIOA_BASE_ADDR + GPIOx_OSPEEDR)
#define GPIOA_PUPDR     REG(GPIOA_BASE_ADDR + GPIOx_PUPDR)
#define GPIOA_IDR       REG(GPIOA_BASE_ADDR + GPIOx_IDR)
#define GPIOA_ODR       REG(GPIOA_BASE_ADDR + GPIOx_ODR)
#define GPIOA_BSRR      REG(GPIOA_BASE_ADDR + GPIOx_BSRR)
#define GPIOA_LCKR      REG(GPIOA_BASE_ADDR + GPIOx_LCKR)
#define GPIOA_AFRL      REG(GPIOA_BASE_ADDR + GPIOx_AFRL)
#define GPIOA_AFRH      REG(GPIOA_BASE_ADDR + GPIOx_AFRH)
#define GPIOA_BRR       REG(GPIOA_BASE_ADDR + GPIOx_BRR)

#define GPIOB_MODER     REG(GPIOB_BASE_ADDR + GPIOx_MODER)
#define GPIOB_OTYPER    REG(GPIOB_BASE_ADDR + GPIOx_OTYPER)
#define GPIOB_OSPEEDR   REG(GPIOB_BASE_ADDR + GPIOx_OSPEEDR)
#define GPIOB_PUPDR     REG(GPIOB_BASE_ADDR + GPIOx_PUPDR)
#define GPIOB_IDR       REG(GPIOB_BASE_ADDR + GPIOx_IDR)
#define GPIOB_ODR       REG(GPIOB_BASE_ADDR + GPIOx_ODR)
#define GPIOB_BSRR      REG(GPIOB_BASE_ADDR + GPIOx_BSRR)
#define GPIOB_LCKR      REG(GPIOB_BASE_ADDR + GPIOx_LCKR)
#define GPIOB_AFRL      REG(GPIOB_BASE_ADDR + GPIOx_AFRL)
#define GPIOB_AFRH      REG(GPIOB_BASE_ADDR + GPIOx_AFRH)
#define GPIOB_BRR       REG(GPIOB_BASE_ADDR + GPIOx_BRR)

#define GPIOC_MODER     REG(GPIOC_BASE_ADDR + GPIOx_MODER)
#define GPIOC_OTYPER    REG(GPIOC_BASE_ADDR + GPIOx_OTYPER)
#define GPIOC_OSPEEDR   REG(GPIOC_BASE_ADDR + GPIOx_OSPEEDR)
#define GPIOC_PUPDR     REG(GPIOC_BASE_ADDR + GPIOx_PUPDR)
#define GPIOC_IDR       REG(GPIOC_BASE_ADDR + GPIOx_IDR)
#define GPIOC_ODR       REG(GPIOC_BASE_ADDR + GPIOx_ODR)
#define GPIOC_BSRR      REG(GPIOC_BASE_ADDR + GPIOx_BSRR)
#define GPIOC_LCKR      REG(GPIOC_BASE_ADDR + GPIOx_LCKR)
#define GPIOC_AFRL      REG(GPIOC_BASE_ADDR + GPIOx_AFRL)
#define GPIOC_AFRH      REG(GPIOC_BASE_ADDR + GPIOx_AFRH)
#define GPIOC_BRR       REG(GPIOC_BASE_ADDR + GPIOx_BRR)

#define GPIOD_MODER     REG(GPIOD_BASE_ADDR + GPIOx_MODER)
#define GPIOD_OTYPER    REG(GPIOD_BASE_ADDR + GPIOx_OTYPER)
#define GPIOD_OSPEEDR   REG(GPIOD_BASE_ADDR + GPIOx_OSPEEDR)
#define GPIOD_PUPDR     REG(GPIOD_BASE_ADDR + GPIOx_PUPDR)
#define GPIOD_IDR       REG(GPIOD_BASE_ADDR + GPIOx_IDR)
#define GPIOD_ODR       REG(GPIOD_BASE_ADDR + GPIOx_ODR)
#define GPIOD_BSRR      REG(GPIOD_BASE_ADDR + GPIOx_BSRR)
#define GPIOD_LCKR      REG(GPIOD_BASE_ADDR + GPIOx_LCKR)
#define GPIOD_AFRL      REG(GPIOD_BASE_ADDR + GPIOx_AFRL)
#define GPIOD_AFRH      REG(GPIOD_BASE_ADDR + GPIOx_AFRH)
#define GPIOD_BRR       REG(GPIOD_BASE_ADDR + GPIOx_BRR)

#define GPIOE_MODER     REG(GPIOE_BASE_ADDR + GPIOx_MODER)
#define GPIOE_OTYPER    REG(GPIOE_BASE_ADDR + GPIOx_OTYPER)
#define GPIOE_OSPEEDR   REG(GPIOE_BASE_ADDR + GPIOx_OSPEEDR)
#define GPIOE_PUPDR     REG(GPIOE_BASE_ADDR + GPIOx_PUPDR)
#define GPIOE_IDR       REG(GPIOE_BASE_ADDR + GPIOx_IDR)
#define GPIOE_ODR       REG(GPIOE_BASE_ADDR + GPIOx_ODR)
#define GPIOE_BSRR      REG(GPIOE_BASE_ADDR + GPIOx_BSRR)
#define GPIOE_LCKR      REG(GPIOE_BASE_ADDR + GPIOx_LCKR)
#define GPIOE_AFRL      REG(GPIOE_BASE_ADDR + GPIOx_AFRL)
#define GPIOE_AFRH      REG(GPIOE_BASE_ADDR + GPIOx_AFRH)
#define GPIOE_BRR       REG(GPIOE_BASE_ADDR + GPIOx_BRR)

#define GPIOF_MODER     REG(GPIOF_BASE_ADDR + GPIOx_MODER)
#define GPIOF_OTYPER    REG(GPIOF_BASE_ADDR + GPIOx_OTYPER)
#define GPIOF_OSPEEDR   REG(GPIOF_BASE_ADDR + GPIOx_OSPEEDR)
#define GPIOF_PUPDR     REG(GPIOF_BASE_ADDR + GPIOx_PUPDR)
#define GPIOF_IDR       REG(GPIOF_BASE_ADDR + GPIOx_IDR)
#define GPIOF_ODR       REG(GPIOF_BASE_ADDR + GPIOx_ODR)
#define GPIOF_BSRR      REG(GPIOF_BASE_ADDR + GPIOx_BSRR)
#define GPIOF_LCKR      REG(GPIOF_BASE_ADDR + GPIOx_LCKR)
#define GPIOF_AFRL      REG(GPIOF_BASE_ADDR + GPIOx_AFRL)
#define GPIOF_AFRH      REG(GPIOF_BASE_ADDR + GPIOx_AFRH)
#define GPIOF_BRR       REG(GPIOF_BASE_ADDR + GPIOx_BRR)

#endif /* REGISTERS_GPIO_H_ */
