/*
 * usart.h
 *
 *  Created on: 25 feb. 2025
 *      Author: geert
 */

#ifndef REGISTERS_USART_H_
#define REGISTERS_USART_H_

#include "reg.h"

#define USART1_BASE_ADDR (0x40013800)
#define USART2_BASE_ADDR (0x40004400)
#define USART3_BASE_ADDR (0x40004800)
#define USART4_BASE_ADDR (0x40004C00)
#define USART5_BASE_ADDR (0x40005000)
#define USART6_BASE_ADDR (0x40011400)
#define USART7_BASE_ADDR (0x40011800)
#define USART8_BASE_ADDR (0x40011C00)

/* address offset for specific usart registers*/
#define USARTx_CR1		(0x00) //USART control register 1
#define USARTx_CR2		(0x04) //USART control register 2
#define USARTx_CR3		(0x08) //USART control register 3
#define USARTx_BRR		(0x0c) //USART baud rate register
#define USARTx_GTPR		(0x10) //USART guard time and prescaler register
#define USARTx_RTOR		(0x14) //USART receiver timeout register
#define USARTx_RQR		(0x18) //USART request register
#define USARTx_ISR		(0x1c) //USART interrupt and status register
#define USARTx_ICR		(0x20) //USART interrupt flag clear register
#define USARTx_RDR		(0x24) //USART receive data register
#define USARTx_TDR		(0x28) //USART transmit data register

#define USART1_CR1      REG(USART1_BASE_ADDR + USARTx_CR1)
#define USART1_CR2      REG(USART1_BASE_ADDR + USARTx_CR2)
#define USART1_CR3      REG(USART1_BASE_ADDR + USARTx_CR3)
#define USART1_BRR      REG(USART1_BASE_ADDR + USARTx_BRR)
#define USART1_GTPR     REG(USART1_BASE_ADDR + USARTx_GTPR)
#define USART1_RTOR     REG(USART1_BASE_ADDR + USARTx_RTOR)
#define USART1_RQR      REG(USART1_BASE_ADDR + USARTx_RQR)
#define USART1_ISR      REG(USART1_BASE_ADDR + USARTx_ISR)
#define USART1_ICR      REG(USART1_BASE_ADDR + USARTx_ICR)
#define USART1_RDR      REG(USART1_BASE_ADDR + USARTx_RDR)
#define USART1_TDR      REG(USART1_BASE_ADDR + USARTx_TDR)

#define USART2_CR1      REG(USART2_BASE_ADDR + USARTx_CR1)
#define USART2_CR2      REG(USART2_BASE_ADDR + USARTx_CR2)
#define USART2_CR3      REG(USART2_BASE_ADDR + USARTx_CR3)
#define USART2_BRR      REG(USART2_BASE_ADDR + USARTx_BRR)
#define USART2_GTPR     REG(USART2_BASE_ADDR + USARTx_GTPR)
#define USART2_RTOR     REG(USART2_BASE_ADDR + USARTx_RTOR)
#define USART2_RQR      REG(USART2_BASE_ADDR + USARTx_RQR)
#define USART2_ISR      REG(USART2_BASE_ADDR + USARTx_ISR)
#define USART2_ICR      REG(USART2_BASE_ADDR + USARTx_ICR)
#define USART2_RDR      REG(USART2_BASE_ADDR + USARTx_RDR)
#define USART2_TDR      REG(USART2_BASE_ADDR + USARTx_TDR)

#define USART3_CR1      REG(USART3_BASE_ADDR + USARTx_CR1)
#define USART3_CR2      REG(USART3_BASE_ADDR + USARTx_CR2)
#define USART3_CR3      REG(USART3_BASE_ADDR + USARTx_CR3)
#define USART3_BRR      REG(USART3_BASE_ADDR + USARTx_BRR)
#define USART3_GTPR     REG(USART3_BASE_ADDR + USARTx_GTPR)
#define USART3_RTOR     REG(USART3_BASE_ADDR + USARTx_RTOR)
#define USART3_RQR      REG(USART3_BASE_ADDR + USARTx_RQR)
#define USART3_ISR      REG(USART3_BASE_ADDR + USARTx_ISR)
#define USART3_ICR      REG(USART3_BASE_ADDR + USARTx_ICR)
#define USART3_RDR      REG(USART3_BASE_ADDR + USARTx_RDR)
#define USART3_TDR      REG(USART3_BASE_ADDR + USARTx_TDR)

#define USART4_CR1      REG(USART4_BASE_ADDR + USARTx_CR1)
#define USART4_CR2      REG(USART4_BASE_ADDR + USARTx_CR2)
#define USART4_CR3      REG(USART4_BASE_ADDR + USARTx_CR3)
#define USART4_BRR      REG(USART4_BASE_ADDR + USARTx_BRR)
#define USART4_GTPR     REG(USART4_BASE_ADDR + USARTx_GTPR)
#define USART4_RTOR     REG(USART4_BASE_ADDR + USARTx_RTOR)
#define USART4_RQR      REG(USART4_BASE_ADDR + USARTx_RQR)
#define USART4_ISR      REG(USART4_BASE_ADDR + USARTx_ISR)
#define USART4_ICR      REG(USART4_BASE_ADDR + USARTx_ICR)
#define USART4_RDR      REG(USART4_BASE_ADDR + USARTx_RDR)
#define USART4_TDR      REG(USART4_BASE_ADDR + USARTx_TDR)

#define USART5_CR1      REG(USART5_BASE_ADDR + USARTx_CR1)
#define USART5_CR2      REG(USART5_BASE_ADDR + USARTx_CR2)
#define USART5_CR3      REG(USART5_BASE_ADDR + USARTx_CR3)
#define USART5_BRR      REG(USART5_BASE_ADDR + USARTx_BRR)
#define USART5_GTPR     REG(USART5_BASE_ADDR + USARTx_GTPR)
#define USART5_RTOR     REG(USART5_BASE_ADDR + USARTx_RTOR)
#define USART5_RQR      REG(USART5_BASE_ADDR + USARTx_RQR)
#define USART5_ISR      REG(USART5_BASE_ADDR + USARTx_ISR)
#define USART5_ICR      REG(USART5_BASE_ADDR + USARTx_ICR)
#define USART5_RDR      REG(USART5_BASE_ADDR + USARTx_RDR)
#define USART5_TDR      REG(USART5_BASE_ADDR + USARTx_TDR)

#define USART6_CR1      REG(USART6_BASE_ADDR + USARTx_CR1)
#define USART6_CR2      REG(USART6_BASE_ADDR + USARTx_CR2)
#define USART6_CR3      REG(USART6_BASE_ADDR + USARTx_CR3)
#define USART6_BRR      REG(USART6_BASE_ADDR + USARTx_BRR)
#define USART6_GTPR     REG(USART6_BASE_ADDR + USARTx_GTPR)
#define USART6_RTOR     REG(USART6_BASE_ADDR + USARTx_RTOR)
#define USART6_RQR      REG(USART6_BASE_ADDR + USARTx_RQR)
#define USART6_ISR      REG(USART6_BASE_ADDR + USARTx_ISR)
#define USART6_ICR      REG(USART6_BASE_ADDR + USARTx_ICR)
#define USART6_RDR      REG(USART6_BASE_ADDR + USARTx_RDR)
#define USART6_TDR      REG(USART6_BASE_ADDR + USARTx_TDR)

#define USART7_CR1      REG(USART7_BASE_ADDR + USARTx_CR1)
#define USART7_CR2      REG(USART7_BASE_ADDR + USARTx_CR2)
#define USART7_CR3      REG(USART7_BASE_ADDR + USARTx_CR3)
#define USART7_BRR      REG(USART7_BASE_ADDR + USARTx_BRR)
#define USART7_GTPR     REG(USART7_BASE_ADDR + USARTx_GTPR)
#define USART7_RTOR     REG(USART7_BASE_ADDR + USARTx_RTOR)
#define USART7_RQR      REG(USART7_BASE_ADDR + USARTx_RQR)
#define USART7_ISR      REG(USART7_BASE_ADDR + USARTx_ISR)
#define USART7_ICR      REG(USART7_BASE_ADDR + USARTx_ICR)
#define USART7_RDR      REG(USART7_BASE_ADDR + USARTx_RDR)
#define USART7_TDR      REG(USART7_BASE_ADDR + USARTx_TDR)

#define USART8_CR1      REG(USART8_BASE_ADDR + USARTx_CR1)
#define USART8_CR2      REG(USART8_BASE_ADDR + USARTx_CR2)
#define USART8_CR3      REG(USART8_BASE_ADDR + USARTx_CR3)
#define USART8_BRR      REG(USART8_BASE_ADDR + USARTx_BRR)
#define USART8_GTPR     REG(USART8_BASE_ADDR + USARTx_GTPR)
#define USART8_RTOR     REG(USART8_BASE_ADDR + USARTx_RTOR)
#define USART8_RQR      REG(USART8_BASE_ADDR + USARTx_RQR)
#define USART8_ISR      REG(USART8_BASE_ADDR + USARTx_ISR)
#define USART8_ICR      REG(USART8_BASE_ADDR + USARTx_ICR)
#define USART8_RDR      REG(USART8_BASE_ADDR + USARTx_RDR)
#define USART8_TDR      REG(USART8_BASE_ADDR + USARTx_TDR)

#endif /* REGISTERS_USART_H_ */
